feat(keybindings): Add keybindings for Graph view, Pages view and Settings view
athensresearch/athens pull request #1192
Opened 2021-05-18 11:03 UTC by sawhney17

Add keybindings for Graph view, Pages view and Settings view

2021-05-18 11:05 UTC, sawhney17 commented
I've added some new keybindings. I followed what made logical sense to me. 

For mac
Option-A: All Pages view
Option-G: Graph View
CMD-COMMA: Settings
For Windows: 
alt-A: All Pages view
alt-G: Graph View
ctrl-COMMA: Settings

First two are in line with what we have done with the daily note shortcut
Cmd-Comma is pretty much the standard across every single app.

2021-05-18 12:09 UTC, Limezy commented
⌘, is very common for the settings on Mac, agreed
⌘G for **G**raph view seems pretty legit
However, I would expect ⌘A to select all blocks in the page, no ?

2021-05-18 13:01 UTC, sawhney17 commented
> ⌘G for **G**raph view seems pretty legit
> However, I would expect ⌘A to select all blocks in the page, no ?

Both of these are **option/alt** not **command/ctrl**. It's similar to the daily notes which is option/alt d. 

Command G is reserved for the querying function or something. Looks like this 
<img width="1440" alt="Screen Shot 2021-05-18 at 6 29 26 PM" src="https://user-images.githubusercontent.com/80150109/118655240-f84c5a00-b806-11eb-8e5f-b82cb583d88a.png">

2021-05-18 13:55 UTC, agentydragon commented
Maybe you could also add the shortcuts into athens/src/cljs/athens/athens_datoms.cljs so people can discover them?

2021-05-18 14:06 UTC, arkRedM requested changes
Very minor suggestions

2021-05-18 14:06 UTC, arkRedM commented on src/cljs/athens/listeners.cljs
> +            KeyCodes.A (router/navigate :pages)
Please do add shortcuts to initial datoms for discoverability until a help popover comes along

2021-05-18 14:21 UTC, sawhney17 commented
@arkRedM I'll get right to adding all of this

2021-05-19 02:51 UTC, Limezy commented
> Both of these are **option/alt** not **command/ctrl**. It's similar to the daily notes which is option/alt d.
Yep sorry I was too fast !

2021-05-19 22:44 UTC, tangjeff0 approved these changes
Way to go @sawhney17 ! Getting into the code 😎

2021-05-19 22:45 UTC, merged