Fix : Clicking inside a block with hyperlink
athensresearch/athens pull request #1236
Opened 2021-05-26 15:22 UTC by sid597

PR  for #1213

2021-05-26 15:23 UTC, sid597 commented
There is a bug in the current implementation due to which block-ref styles are not applied. This PR is more of a draft to show my current approach.

2021-05-26 21:19 UTC, sid597 commented
Fixed the issue by using pointer-events, tested on a few custom blocks which contain all type of elements.

2021-06-07 07:51 UTC, neotyk requested changes
Using CamelCase is not very idiomatic Clojure, please use kebab-case for var, fn, keyword names.
In this particular instance `:textRun` -> `:text-run`.

Apart from it LGTM, Thank you :-)

2021-06-07 07:51 UTC, neotyk commented on test/athens/parser/compatibility_test.clj
> +      [:testRun
it should be `textRun`

2021-06-07 20:53 UTC, tangjeff0 requested changes
see Alex's requests

2021-06-08 00:21 UTC, sid597 commented on test/athens/parser/compatibility_test.clj
> +      [:testRun
Aha!, Thank you, Alex.

2021-06-08 00:22 UTC, sid597 commented
Thank you Alex for reviewing this, more PR's coming your way from my side :)

2021-06-09 14:14 UTC, tangjeff0 approved these changes

2021-06-09 14:14 UTC, merged