fix: Some bullets are not round
athensresearch/athens pull request #1568
Opened 2021-08-20 12:16 UTC by juniusfree

fix #1495

2021-08-20 12:29 UTC, filipesilva reviewed
I'm a bit confused as to why this is the right fix, the border radius has not changed in a while.

Could effecting this change actually be hiding the real problem, where a bullet might be rendered twice?

2021-08-20 12:57 UTC, neotyk commented
> I'm a bit confused as to why this is the right fix, the border radius has not changed in a while.
> 
> Could effecting this change actually be hiding the real problem, where a bullet might be rendered twice?

I've checked it looks like there is just 1 element.
Not sure how we got here, I'll add it to result of css-garden approach.

2021-08-20 13:10 UTC, filipesilva commented
@neotyk I defer to you, you have a much better understanding of this.

2021-08-20 14:09 UTC, juniusfree commented
I might have rushed this one because I can see a subtle difference after the update (or am I? 😵). I'll try to investigate if this has deeper issues.

2021-08-20 14:40 UTC, shanberg commented
I think the answer here is we should be using SVG circles instead of pseudo-elements.

If the DOM is telling the bullet to be taller than it is wide or wider than it is tall, the only change we've made is that it'll be elliptical rather than squarish, and we haven't told the browser to keep it always the same width/height. A very simple SVG should have an easier time staying at a 1:1 aspect ratio.

2021-08-21 14:29 UTC, shanberg commented
It looks like I misunderstood the nature of this problem.

I had assumed that something was squishing the bullet and we just needed to use a stronger method of defining its shape but I'm still seeing cases where some bullets are elliptical, even with the SVG.

What seemed to solve all cases is to add `transform: scale(1.01)` to the bullet SVG. I'm not absolutely sure why, but given that the calculated size of the bullets has always been squared, I'm guessing it changes the way the element treats subpixels during rendering. Regardless, this is the fix I recommend at this point. It’s essentially a hack, but not anything fundamentally crazy or likely to cause further issues.
- - -
Note: Switching from `em` units to `px` units in `bullet-style` fixed the shape, but the `em` units allow the bullets (and everything else in blocks) to scale down in the sidebar, so switching to `px` units isn't a magic wand and I don't recommend it.

2021-08-21 14:34 UTC, shanberg commented on src/cljs/athens/views/blocks/bullet.cljs
> +                               :transition "color 0.05s ease, opacity 0.05s ease, box-shadow 0.05s ease, transform 0.05s ease"}]
```suggestion
   ::stylefy/manual [[:svg {:transform "scale(1.001)" ;; Prevents the bullet being squished
                            :overflow "visible" ;; Prevents the stroke from being cropped
                            }]
                     [:circle {:fill "currentColor"
                               :transition "color 0.05s ease, opacity 0.05s ease, box-shadow 0.05s ease, transform 0.05s ease"}]
```

2021-08-21 14:35 UTC, shanberg commented on src/cljs/athens/views/blocks/bullet.cljs
> +                                                        :stroke-width "4"
Update the style to look closer to the previous bullets

```suggestion
                                                        :fill (style/color :body-text-color :opacity-low)
                                                        :r "22"
                                                        :stroke-width "12"
```

2021-08-21 14:37 UTC, shanberg requested changes
I was wrong about SVG fixing it, but switching to SVG is better for a bunch of reasons anyway. 

I've suggested a new fix for the bullet squishing.

2021-08-24 20:37 UTC, shanberg approved these changes

2021-08-24 21:30 UTC, merged