fix: bullet too small
athensresearch/athens pull request #1595
Opened 2021-08-25 21:41 UTC by juniusfree

fix https://discord.com/channels/708122962422792194/708124073544122399/880029228458975233

2021-08-30 10:06 UTC, filipesilva commented
Followup fix for #1495

2021-09-02 12:13 UTC, shanberg commented on src/cljs/athens/views/blocks/bullet.cljs
> +                            :height "0.5em"}]
```suggestion
                            :width "0.375em"
                            :height "0.375em"}]
```

2021-09-02 12:22 UTC, shanberg requested changes
I had to go back to the mockups to recall the exact intended size after seeing it so many different ways. The size of the anchor on a regular block at the base zoom level is 6px. It looks like the first fix made the anchor too small, your fix made the anchor slightly too big, and the `0.375em` size should make it the correct size.

With my suggestion:
<img width="515" alt="CleanShot 2021-09-02 at 08 18 41@2x" src="https://user-images.githubusercontent.com/98312/131842186-9daf3b26-eda6-46dd-ad91-07d9e2e3edc1.png">

The mockup/source of truth:
<img width="342" alt="CleanShot 2021-09-02 at 08 19 38@2x" src="https://user-images.githubusercontent.com/98312/131842315-e9fb9c40-f18e-4b90-a2da-c236c816cf58.png">

I'm hopeful that certain unrelated front-end refactoring will make this kind of issue easier to identify and fix in the future.

2021-09-02 12:30 UTC, shanberg approved these changes

2021-09-02 12:46 UTC, merged