Fix-misc-new-layout-issues
athensresearch/athens pull request #2282
Opened 2022-08-16 00:18 UTC by shanberg

- Fix extra daily notes appearing
- Refactor toolbar button props
- Fix console error related to right sidebar
- Make backgrounds transition evenly when changing theme

2022-08-16 09:35 UTC, filipesilva requested changes
Slash command seems to get into a weird position sometimes:

This was ok
<img width="597" alt="image" src="https://user-images.githubusercontent.com/4172079/184847500-9f9047fd-485a-449c-991c-0e77865d7da3.png">

But calling it on the second daily note shows it in a different place:
<img width="521" alt="image" src="https://user-images.githubusercontent.com/4172079/184847591-cbf239c2-7251-4f82-8932-03ac76e7af2a.png">

After calling and dismissing it on the first daily note, hovering around the note shows the menu from the top left corner
<img width="326" alt="image" src="https://user-images.githubusercontent.com/4172079/184847845-6cc76b43-e685-4a6a-a699-3f668c29d1a6.png">

2022-08-16 09:35 UTC, filipesilva commented on src/js/components/Layout/RightSidebar.tsx
> +  console.log(rightSidebarWidth)
Nit: remove debug code

2022-08-16 11:31 UTC, shanberg commented on src/js/components/Layout/RightSidebar.tsx
> +  console.log(rightSidebarWidth)
🤦

2022-08-17 14:24 UTC, filipesilva approved these changes

2022-08-17 14:36 UTC, merged