Fix comments not rendering
athensresearch/athens pull request #2307
Opened 2022-08-24 11:57 UTC by sid597

2022-08-24 13:49 UTC, neotyk approved these changes
LGTM

2022-08-24 13:49 UTC, neotyk commented on src/cljs/athens/views/pages/block_page.cljs
> +        is-editing?                    (subscribe [:editing/is-editing uid])
Please use qualified version `rf/subscribe`

2022-08-24 16:53 UTC, tangjeff0 requested changes
When I click on different notification messages, I see that the URL updates with a new block-uid, but the UI doesnt change.

2022-08-25 08:59 UTC, tangjeff0 approved these changes

2022-08-25 09:00 UTC, merged