feat: self-hosted real-time collab and presence
athensresearch/athens pull request #930
Opened 2021-04-09 15:23 UTC by tangjeff0

2021-04-09 20:33 UTC, arkRedM commented
Next steps
1. Basic -- lint, style
2. a. Clarification: For auth, a token and ip shared with folks is enough (username and pass doesn't add much) 
    b. Add option to switch between connection to remote graph and local graph.
3. One-click deploy to  ___? (heroku | some other prov?)

2021-04-09 20:43 UTC, arkRedM requested changes

2021-04-09 20:43 UTC, arkRedM commented on shadow-cljs.edn
> + :nrepl {:port 8778}
revert

2021-04-09 20:43 UTC, arkRedM commented on shadow-cljs.edn
> +                                  :http-port    3001}}
revert

2021-04-11 16:03 UTC, agentydragon requested changes
Nice work. I think it might take a bit more to get it ready.

Couple high level things:

- I believe we ended up deciding to put the server into the same repo, right? Can you add the server into the PR?

- Since it might take a bit to get into good state, I'd recommend submitting separately whatever can be submitted separately. For example, the display name stuff and maybe the presence Reagent component could be submitted (maybe with tests, too) separately. Code can also be behind a feature flag (though I believe Athens doesn't right now have feature flags...)

2021-04-11 16:55 UTC, agentydragon commented on src/cljs/athens/views/settings_page.cljs
> +                                    (js/localStorage.setItem "user/name" (.. % -target -value)))}]
https://github.com/Day8/re-frame/blob/master/docs/Effects.md says re-frame has built-in effects for setting local store stuff

https://github.com/Day8/re-frame/blob/master/docs/Effects.md#the-effects-map

2021-04-12 17:11 UTC, tangjeff0 commented on project.clj
> +                 [datsync "0.0.1-alpha2-SNAPSHOT"]]
Used in `src/cljs/athens/datsync_utils.cljs`

2021-04-12 19:32 UTC, tangjeff0 reviewed
Some thoughts:

- Reconnection doesn't seem to work if a computer sleeps and awakens
- Definitely need to move db picker into settings, getting crowded now. CC @shanberg 
- `You` in top right always seems to say `You`. Seems like there should be other user names if they are on the same page.
![image](https://user-images.githubusercontent.com/8952138/114450442-dcf88a00-9b8a-11eb-9a52-9e9fb9e82f93.png)
- Seems like the ability to "Follow" a user while they navigate to other pages or see what page they are on at the moment would be nice.
- Need to click on the People icon to see if the name of the User that is there. Hover probably makes more sense
![image](https://user-images.githubusercontent.com/8952138/114450640-1d580800-9b8b-11eb-8f76-ac09608d406c.png)

2021-04-12 20:00 UTC, agentydragon commented
> Seems like the ability to "Follow" a user while they navigate to other pages or see what page they are on at the moment would be nice.

Agree, but I think this would be better left for later, to make the initial version smaller.

2021-04-12 20:01 UTC, agentydragon commented on project.clj
> +                 [datsync "0.0.1-alpha2-SNAPSHOT"]]
ah, you're right.

but then, still, depending on a SNAPSHOT version does not sound to me like a good idea. could we

2021-04-12 20:06 UTC, agentydragon commented on src/cljs/athens/views/presence.cljs
> +                                                 (= (:editing/uid %) ctx-uid))))
also the predicate shares a bunch with lines 43..47

2021-04-14 16:28 UTC, arkRedM commented
> Pressing enter at the same time under the same parent
This should be done a little cleaner I agree. Too many bad nodes are not ideal.

> Reconnection doesn't seem to work if a computer sleeps and awakens
This is probably a must. I think I should come up with a bare min reconnection logic.

2021-04-14 17:04 UTC, arkRedM commented
> You in top right always seems to say You. Seems like there should be other user names if they are on the same page.

it should come up as "You" or "You and n others". Will look into it

2021-04-15 14:39 UTC, tangjeff0 commented
Btw, I'm not exactly sure what your timeline looks like right now, so I've been working off of your branch @arkRedM in case you're availability is limited/variable: https://github.com/arkRedM/athens/pull/1

2021-04-16 16:50 UTC, tangjeff0 commented
Getting this error when deleting block(s):

![image](https://user-images.githubusercontent.com/8952138/115057675-31f11480-9e99-11eb-9db2-5242fbc86ec2.png)

2021-04-17 04:07 UTC, tangjeff0 commented
@arkRedM might be good to merge/rebase  what I've done in on my `presence` branch. Some small refactors and fixes.

2021-04-17 05:10 UTC, arkRedM commented
> @arkRedM might be good to merge/rebase what I've done in on my `presence` branch. Some small refactors and fixes.

Oh! I did the exact same changes 🙆‍♂️(with slight differences)

2021-04-17 05:13 UTC, arkRedM commented
Okay too many commits and diffs, easier thing is I go over commits from your branch one by one and add the final version. @tangjeff0  how does that sound?

2021-04-17 06:12 UTC, arkRedM commented
> Okay too many commits and diffs, easier thing is I go over commits from your branch one by one and add the final version. @tangjeff0 how does that sound?

Went ahead and did that(took credit for your commits :P)

2021-04-17 23:20 UTC, tangjeff0 commented
Would be ideal if there was documentation on how this was architected. https://github.com/athensresearch/athens-backend should also have setup instructions, including how to migrate from local datascript `index.transit` to datahike for our enterprise customers.

2021-04-18 00:33 UTC, arkRedM commented
> setup instructions
Figuring out some parts will add it once everything is clear 😅

2021-04-18 16:42 UTC, merged